[package]
name = "unityjaeger/bolt"
description = "Custom collision detection"
authors = ["unityjaeger"]
version = "0.1.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"
repository = "https://github.com/unityjaeger/Bolt"
include = [
	"default.project.json",
	"wally.toml",
    "wally.lock",
	"LICENSE",
    "src",
    "src/**/*"
]
exclude = ["**"]